import Head from "next/head";
import Menu from "../components/menu/Menu";
import Hero from "../components/strony-www/Hero"
import Footer from "../components/footer/Footer";
import { useEffect, useState } from "react";
import axios from "../axios";
import ContactButton from "../components/utils/ContactButton";

export default function Home() {
    const [api, setApi] = useState([]);
    const getAPI = async () => {
        await axios
            .get("/pozycjonowanie")
            .then((res) => {
                console.log(res);
                setApi(res.data);
            })
            .catch((err) => console.log(err));
    };

    useEffect(() => {
        getAPI();
        console.log(api);
        console.log(api.MetaTitle);
    }, []);
    return (
        <div>
            <Head>
                <title>{api.MetaTitle}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon1.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,600;0,800;1,100;1,300;1,400;1,600;1,800&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Menu />
            <Hero title2={api.Title} text={api.HeroText} image="/images/seoImage.svg" />
            <ContactButton />
            <Footer />
        </div>
    );
}
